---
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.6.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/ansible-community/antsibull-changelog.git
    rev: 0.28.0
    hooks:
      - id: antsibull-changelog-lint
      - id: antsibull-changelog-lint-changelog-yaml
