---
- name: Include get vms task
  ansible.builtin.include_tasks: vms/get.yml
  vars:
    app_tag: execution
    private_host_groups:
      - aap
      - execution_private
    public_host_groups:
      - execution_public

- name: Set number of execution node VMs to create
  ansible.builtin.set_fact:
    infrastructure_execution_vms_to_create: "{{ (infrastructure_virtual_machines | selectattr('name', 'eq', 'execution') | first).instances -
      (infrastructure_existing_vm.vms | default([]) | length) }}"

- name: Output number of VMs to create
  ansible.builtin.debug:
    msg: "Creating execution VMs: {{ infrastructure_execution_vms_to_create }}"

- name: Include create vm task
  ansible.builtin.include_tasks: vms/create.yml
  loop: "{{ range(infrastructure_execution_vms_to_create | int) }}"
  vars:
    app_tag: execution
    instance_type: "{{ (infrastructure_virtual_machines | selectattr('name', 'eq', 'execution') | first).shape }}"
    private_host_groups:
      - aap
      - execution_private
    public_host_groups:
      - execution_public
    subnet: "{{ infrastructure_subnet_names | select('search', 'execution') | first }}"
