---
- name: Include get vms task
  ansible.builtin.include_tasks: vms/get.yml
  vars:
    app_tag: hub
    private_host_groups:
      - aap
      - hub_private
    public_host_groups:
      - hub_public

- name: Set number of hub VMs to create
  ansible.builtin.set_fact:
    infrastructure_hub_vms_to_create: "{{ (infrastructure_virtual_machines | selectattr('name', 'eq', 'hub') | first).instances -
      (infrastructure_existing_vm.vms | default([]) | length) }}"

- name: Output number of VMs to create
  ansible.builtin.debug:
    msg: "Creating hub VMs: {{ infrastructure_hub_vms_to_create }}"

- name: Include create vm task
  ansible.builtin.include_tasks: vms/create.yml
  loop: "{{ range(infrastructure_hub_vms_to_create | int) }}"
  vars:
    app_tag: hub
    instance_type: "{{ (infrastructure_virtual_machines | selectattr('name', 'eq', 'hub') | first).shape }}"
    private_host_groups:
      - aap
      - hub_private
    public_host_groups:
      - hub_public
    subnet: "{{ infrastructure_subnet_names | select('search', 'hub') | first }}"
