---
- name: Create VM facts
  ansible.builtin.set_fact:
    vm_name: "aap-infrastructure-{{ deployment_id }}-vm-{{ vm_name_prefix | default('') }}{{ query('community.general.random_string', upper=false, numbers=false, special=false) | first }}"  # noqa yaml[line-length]
  tags:
    - controller
    - hub
    - eda

- name: Debug VM name
  ansible.builtin.debug:
    var: vm_name
  tags:
    - controller
    - hub
    - eda

- name: Gather public IP address
  azure.azcollection.azure_rm_publicipaddress_info:
    resource_group: "{{ resource_group }}"
    name: "pip-{{ app_tag }}"
  register: infrastructure_virtual_machine_public_ip
  tags:
    - controller
    - hub
    - eda

- name: Create virtual machines
  vars:
    vm_additional_tags:
      Name: "{{ vm_name }}"
      app: "{{ app_tag | default('') }}"
    vm_tags: "{{ vm_additional_tags | combine(_infrastructure_tags) }}"
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    ssh_public_keys: "{{ infrastructure_ssh_public_keys }}"
    vm_size: "{{ instance_type }}"
    admin_username: "{{ infrastructure_admin_username }}"
    ssh_password_enabled: "{{ infrastructure_password_enabled }}"
    network_interfaces: "nic-{{ deployment_id }}-{{ app_tag }}"
    managed_disk_type: "{{ infrastructure_managed_disk_type }}"
    os_disk_size_gb: "{{ infrastructure_os_disk_size_gb }}"
    image: "{{ infrastructure_ami }}"
    location: "{{ infrastructure_region }}"
    tags: "{{ vm_tags }}"
  register: infrastructure_virtual_machine
  tags:
    - controller
    - hub
    - eda

- name: Output the IP of new VM
  ansible.builtin.debug:
    msg:
      - "Public IP for {{ vm_name }}: {{ infrastructure_virtual_machine_public_ip.publicipaddresses[0].ip_address | default('') }}"
      - "Private IP for {{ vm_name }}: {{ infrastructure_virtual_machine.ansible_facts.azure_vm.network_profile.network_interfaces[0].properties.ip_configurations[0].private_ip_address | default('') }}"
  when:
    - infrastructure_virtual_machine_public_ip.publicipaddresses is defined
    - infrastructure_virtual_machine_public_ip.publicipaddresses | length > 0
    - infrastructure_virtual_machine.ansible_facts.azure_vm.network_profile.network_interfaces is defined
    - infrastructure_virtual_machine.ansible_facts.azure_vm.network_profile.network_interfaces | length > 0
  tags:
    - controller
    - hub
    - eda

- name: Set stats for Controller of new VM
  ansible.builtin.set_stats:
    data:
      "{{ vm_name | replace('-','_') }}_priv_network_private_ip": "{{ infrastructure_virtual_machine.ansible_facts.azure_vm.network_profile.network_interfaces[0].properties.ip_configurations[0].private_ip_address | default('') }}"
      "{{ vm_name | replace('-','_') }}_public_ip": "{{ infrastructure_virtual_machine_public_ip.publicipaddresses[0].ip_address | default('') }}"
  when:
    - infrastructure_virtual_machine_public_ip.publicipaddresses is defined
    - infrastructure_virtual_machine_public_ip.publicipaddresses | length > 0
    - infrastructure_virtual_machine.ansible_facts.azure_vm.network_profile.network_interfaces is defined
    - infrastructure_virtual_machine.ansible_facts.azure_vm.network_profile.network_interfaces | length > 0
  tags:
    - controller
    - hub
    - eda

- name: Add public IP host to installer
  when: groups.installer is not defined
  ansible.builtin.add_host:
    groups:
      - installer
    name: "{{ infrastructure_virtual_machine_public_ip.publicipaddresses[0].ip_address }}"
  tags:
    - controller
    - hub
    - eda

- name: Add public IP hosts to group
  ansible.builtin.add_host:
    groups: "{{ public_host_groups + ['public'] | default(['public']) }}"
    name: "{{ infrastructure_virtual_machine_public_ip.publicipaddresses[0].ip_address }}"
  tags:
    - controller
    - hub
    - eda

- name: Add private IPs hosts to group
  ansible.builtin.add_host:
    groups: "{{ private_host_groups + ['private'] | default(['private']) }}"
    name: "{{ infrastructure_virtual_machine.ansible_facts.azure_vm.network_profile.network_interfaces[0].properties.ip_configurations[0].private_ip_address }}"
  tags:
    - controller
    - hub
    - eda
