---
- name: "Check if the {{ app_tag }} VMs are already provisioned"
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{ resource_group }}"
    tags:
      - deployment:aap-infrastructure-{{ deployment_id }}
      - app:{{ app_tag }}
  register: infrastructure_existing_vm

- name: Get VM IPs
  when:
    - infrastructure_existing_vm.vms is defined
    - infrastructure_existing_vm.vms | length > 0
  block:
    - name: Output number of existing VMs
      ansible.builtin.debug:
        msg: "Number of existing {{ app_tag }} VMs: {{ infrastructure_existing_vm.vms | length }}"

    - name: Ensure existing VMs are running
      azure.azcollection.azure_rm_virtualmachine:
        name: "{{ item }}"
        resource_group: "{{ resource_group }}"
        started: true
      loop: "{{ infrastructure_existing_vm.vms | map(attribute='name') | list }}"
      register: infrastructure_running_vm

    - name: Gather public IP address
      azure.azcollection.azure_rm_publicipaddress_info:
        resource_group: "{{ resource_group }}"
        name: "{{ item.ansible_facts.azure_vm.network_profile.network_interfaces[0].properties.ip_configurations[0].public_ip_address.name }}"
      loop: "{{ infrastructure_running_vm.results }}"
      register: infrastructure_running_virtual_machine_public_ip

    - name: Add public IP hosts to group
      ansible.builtin.add_host:
        groups: "{{ public_host_groups + ['public'] | default(['public']) }}"
        name: "{{ item.publicipaddresses[0].ip_address }}"
      loop: "{{ infrastructure_running_virtual_machine_public_ip.results }}"
      changed_when: false

    - name: Add private IPs hosts to group
      ansible.builtin.add_host:
        groups: "{{ private_host_groups + ['private'] | default(['private']) }}"
        name: "{{ item.ansible_facts.azure_vm.network_profile.network_interfaces[0].properties.ip_configurations[0].private_ip_address }}"
      loop: "{{ infrastructure_running_vm.results }}"
      changed_when: false
