---
- name: "Check if the {{ app_tag }} VMs are already provisioned"
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{ resource_group }}"
    tags:
      - deployment:aap-infrastructure-{{ deployment_id }}
      - app:{{ app_tag }}
  register: infrastructure_existing_vm
  tags:
    - controller

- name: Output number of existing VMs
  ansible.builtin.debug:
    msg: "Number of existing {{ app_tag }} VMs: {{ infrastructure_existing_vm.vms | length }}"
  when:
    - infrastructure_existing_vm.vms is defined
  tags:
    - controller

- name: Ensure existing VMs are running
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ item }}"
    resource_group: "{{ resource_group }}"
  loop: "{{ infrastructure_existing_vm.vms | map(attribute='name') | list }}"
  when: infrastructure_existing_vm.vms | length > 0
  register: infrastructure_running_vm
  tags:
    - controller

- name: Gather public IP address
  azure.azcollection.azure_rm_publicipaddress_info:
    resource_group: "{{ resource_group }}"
    name: "pip-{{ app_tag }}"
  when: infrastructure_existing_vm.vms | length > 0
  register: infrastructure_running_virtual_machine_public_ip
  tags:
    - controller

- name: Add public IP hosts to group
  ansible.builtin.add_host:
    groups: "{{ public_host_groups + ['public'] | default(['public']) }}"
    name: "{{ infrastructure_running_virtual_machine_public_ip.publicipaddresses[0].ip_address }}"
  tags:
    - controller

- name: Add private IPs hosts to group
  ansible.builtin.add_host:
    groups: "{{ private_host_groups + ['private'] | default(['private']) }}"
    name: "{{ infrastructure_running_vm.results[0].ansible_facts.azure_vm.network_profile.network_interfaces[0].properties.ip_configurations[0].private_ip_address }}"  # noqa yaml[line-length]
  tags:
    - controller
