---
- name: Deploy Azure infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - lab.azure_deployment.infrastructure

- name: Ensure VMs are up-to-date
  hosts: public
  gather_facts: true
  become: true
    tasks:
    - name: Register subscription manager
      community.general.redhat_subscription:
        state: present
        username: "{{ aap_red_hat_username }}"
        password: "{{ aap_red_hat_password }}"
        auto_attach: true

    - name: Ensure rhsm is managing repos
      ansible.builtin.lineinfile:
        path: /etc/rhsm/rhsm.conf
        regexp: '^manage_repos = '
        line: manage_repos = 1

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Check if reboot is required
      ansible.builtin.command:
        cmd: dnf needs-restarting --reboothint
      changed_when: reboot.rc == 1
      failed_when: false
      register: reboot

    - name: Reboot if there were kernel changes
      ansible.builtin.reboot:
      when: reboot.rc != 0
  
- name: Prepare AAP install
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    aap_controller_hosts: "{{ groups.controller_private }}"
    # aap_ee_hosts: "{{ groups.execution_private | default('') }}"
    aap_hub_hosts: "{{ groups.hub_private | default('') }}"
    # aap_eda_hosts: "{{ groups.eda_private | default('') }}"
    # aap_eda_allowed_hostnames: "{{ (groups.eda_public | default([])) | join(',') }}"
    aap_db_host: "{{ hostvars.localhost.result.response[0].properties.fullyQualifiedDomainName }}"
    - name: Run AAP role
      ansible.builtin.include_role:
        name: lab.azure_deployment.prepare_aap
      tags:
        - controller
        - hub
        - eda
