---
- name: Get deployment VMs
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check for the resource group
      azure.azcollection.azure_rm_resourcegroup_info:
        name: "{{ resource_group }}"
      register: rg

    - name: End the play if there is no resource group
      ansible.builtin.meta: end_host
      when: rg.resourcegroups | length == 0

    - name: Get the existing VMs
      azure.azcollection.azure_rm_publicipaddress_info:
        resource_group: "{{ resource_group }}"
      register: public_ips

    - name: Add the public IP to the aap group
      when:
        - public_ips is defined
        - public_ips.publicipaddresses | length > 0
      ansible.builtin.add_host:
        groups:
          - aap
        name: "{{ item.ip_address }}"
      loop: "{{ public_ips.publicipaddresses }}"

- name: Remove RHEL entitlements
  hosts: aap
  gather_facts: false
  become: true
  tasks:
    - name: Check for required variables
      ansible.builtin.assert:
        that:
          - aap_red_hat_username is defined
          - aap_red_hat_username | length > 0
          - aap_red_hat_password is defined
          - aap_red_hat_password | length > 0

    - name: Unregister subscription manager
      community.general.redhat_subscription:
        state: absent
        username: "{{ aap_red_hat_username }}"
        password: "{{ aap_red_hat_password }}"

- name: Destroy Azure infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get facts by tags
      azure.azcollection.azure_rm_resourcegroup_info:
        name: "{{ resource_group }}"
        list_resources: true
      register: resource_group_info

    - name: Show resources
      ansible.builtin.set_fact:
        target_resources: "{{ resource_group_info.resourcegroups[0].resources | selectattr('tags.' + target_tag, 'defined') | map(attribute='id') | list }}"

    - name: Delete Resource
      loop: "{{ target_resources }}"
      azure.azcollection.azure_rm_resource:
        url: "{{ item }}"
        state: absent
